---
swagger: "2.0"
info:
  x-ibm-name: "apidevops"
  title: "API_Devops"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/apidevops"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        target-url: "$(target-url)$(request.path)"
  phase: "realized"
paths:
  /jenkins_build:
    get:
      responses:
        200:
          description: "200 OK"
      parameters:
      - name: "build_no"
        type: "string"
        required: false
        in: "query"
definitions: {}
tags: []
